[package]
name = "sotor"
version = "0.0.0"
authors = ["Starfish Xeno"]
edition = "2021"
rust-version = "1.74"
build = "src-tauri/build.rs"

[[bin]]
name = "sotor"
path = "src-tauri/main.rs"

[workspace]
members = ["src-tauri/macros"]

[lints]
workspace = true

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
ignored_unit_patterns = "allow"
missing_panics_doc = "allow"
match_on_vec_items = "allow"
module_name_repetitions = "allow"
cast_sign_loss = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_lossless = "allow"

[dependencies]
sotor_macros = { path = "./src-tauri/macros" }
chrono = "0.4.31"
tauri = { version = "1.2", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
typeshare = "1.0.1"


[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
lto = true
