[package]
name = "sotor"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[workspace]
members = ["macros"]

[lints]
workspace = true

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
ignored_unit_patterns = "allow"
missing_panics_doc = "allow"
match_on_vec_items = "allow"
module_name_repetitions = "allow"
cast_sign_loss = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_lossless = "allow"

[dependencies]
sotor_macros = { path = "./macros" }
emath = "0.24.1"
time = { version = "0.3.31", features = ["macros"] }
serde = { version = "1.0.193", features = ["derive"] }
egui = "0.24.1"
eframe = { version = "0.24.1", default-features = false, features = [
    "glow", # Use the glow rendering backend. Alternative: "wgpu".
] }
log = "0.4"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.10"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"


[profile.release]
opt-level = 2 # fast and small wasm
lto = true

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
