[package]
name = "sotor"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[workspace]
members = ["macros"]

[lints]
workspace = true


[workspace.lints.clippy]
pedantic = "warn"
ignored_unit_patterns = "allow"
missing_panics_doc = "allow"
match_on_vec_items = "allow"
module_name_repetitions = "allow"
cast_sign_loss = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_lossless = "allow"

[dependencies]
sotor_macros = { path = "./macros" }
ahash = "0.8.7"
bytemuck = "1.14.0"
rfd = { version = "0.12.1" }
image = { version = "0.24", default-features = false, features = ["tga"] }
time = { version = "0.3.31", features = ["macros"] }
fastrand = "2.0.1"
futures-lite = "2.1.0"
serde = { version = "1.0.193", features = ["derive"] }
log = "0.4"
egui = "0.25"
eframe = { version = "0.25", default-features = false, features = [
    "persistence",
    "glow",
] }
emath = "0.25"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.10"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 3
