[build.env]
volumes = ["STEAM_APPS"]
passthrough = ["STEAM_APPS"]

[target.x86_64-unknown-linux-gnu]
image = "amd64/ubuntu:24.04"
pre-build = [
    "apt-get update && apt-get install build-essential libglib2.0-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev -y",
]
